version: "3"
services:

  

  web:
    restart: "no"
    container_name: task_stepantsov
    build:
      context: ./
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      # Log settings
      LOG_LVL: INFO
      APP_HOST: 0.0.0.0
      APP_PORT: 80
      TRANSFORMERS_CACHE: ./volume/hg_cache
      # Volume settings
      VOLUME_DIR: volume
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=llm_secret
      - POSTGRES_USER=llm_user
      - POSTGRES_DB=llm_dialogues

  